apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: your-image:tag
          env:
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: FLASK_ENV
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DATABASE_URL
          ports:
            - containerPort: 5000