apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: agostinadevdc/finanzas_py:latest
          env:
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: FLASK_ENV
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db:5432/$(POSTGRES_DB)"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials  # Defined on secrets.yaml
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials  # Defined on secrets.yaml
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-credentials  # Defined on secrets.yaml
                  key: POSTGRES_DB
          ports:
            - containerPort: 5000