# This is an example of how to set up your secret in Kubernetes environment. Place this file in .dockerignore and .gitignore. DO NOT UPLOAD your sensitive information, keep it local.
# If you ignored this file on docker/git you must rename the file to secret.yaml to work with deployment.yaml

apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  POSTGRES_USER: <base64-encoded-username>
  POSTGRES_PASSWORD: <base64-encoded-password>
  POSTGRES_DB: mydatabase  # Database name

# Follow these steps to base64 encode your sensitive credentials:
# 1. Run the following command to encode the username:
#    echo -n "userExample" | base64
#    Replace <base64-encoded-username> with the generated base64 value.

# 2. Run the following command to encode the password:
#    echo -n "passwordExample" | base64
#    Replace <base64-encoded-password> with the generated base64 value.
