# For showcasing your Flask app in Kubernetes, use "type: NodePort" to easily expose it
# on a specific port across all nodes. This simplifies access via any node's IP and the
# NodePort, like: http://node-ip:NodePort. It's ideal for small projects or demos where
# simplicity and direct access are more important than automatic load balancing.
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
