apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer  # Puede ser NodePort o LoadBalancer dependiendo de tu entorno
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000